### ISSUE TITLE
What type of value can be used as a field for Geocode on vectormap

### ISSUE THREAD

**Issue by syljac** [stormpython/vectormap#10]
Hi there, I use Kibana with Elasticsearch.
I am familiar with the geo_point type which I use with the default Kibana-maps.
However, I haven't been able to get the vectormap to work with my data.
Can you please tell me what should be the 'type' of the data and an example that would get plotted on the map?

Thanks!

**Comment by stormpython** [comment]
@syljac this plugin only works for terms aggregations, since it expects string values. For example, country codes or state codes, like GA or CA. It will not work for the geo_point type. Kibana already has a tile map visualization that works for those. For more information, check out [jvectormap](http://jvectormap.com/maps/world/world/).
